sensors:

  kts1_camera:
    visualize_fov: true
    type: rgb_camera
    pose:
      xyz: [-1.3, -6.0, 1.44]
      rpy: [pi, pi/2, pi/2]
  
  kts2_camera:
    visualize_fov: true
    type: rgb_camera
    pose:
      xyz: [-1.3, 6.0, 1.44]
      rpy: [pi, pi/2, -pi/2]

  logical_camera_1:
    visualize_fov: true
    type: advanced_logical_camera
    pose:
      xyz: [-2.30, -3.00, 1.80]
      rpy: [1.570797, 1.570797, 1.570797]
  logical_camera_0:
    visualize_fov: true
    type: advanced_logical_camera
    pose:
      xyz: [-2.30, 3.00, 1.80]
      rpy: [1.570797, 1.570797, 1.570797]
      


  logical_camera_conveyor:
    visualize_fov: true
    type: advanced_logical_camera
    pose:
      xyz: [-0.573076, 3.3, 1.90]
      rpy: [1.570797, 1.570797, 1.570797]     



# sensors:
#   right_bins_camera:
#     type: advanced_logical_camera
#     pose:
#       xyz: [-2.286, 2.96, 1.8]
#       rpy: [pi, pi/2, 0]

#   left_bins_camera:
#     type: advanced_logical_camera
#     pose:
#       xyz: [-2.286, -2.96, 1.8]
#       rpy: [pi, pi/2, 0]

#   kts1_camera:
#     type: advanced_logical_camera
#     pose:
#       xyz: [-1.3, -5.8, 1.8]
#       rpy: [pi, pi/2, pi/2]
  
#   kts2_camera:
#     type: advanced_logical_camera
#     pose:
#       xyz: [-1.3, 5.8, 1.8]
#       rpy: [pi, pi/2, -pi/2]
  